spring:
  cloud:
    gateway:
      routes:
        - id: productos-service
          uri: lb://chat-service
          predicates:
            - Path=/api/chat/**
          filters:
            - StripPrefix=2
        - id: clientes-service
          uri: lb://clientes-service
          predicates:
            - Path=/api/clientes/**
          filters:
            - StripPrefix=2
        - id: ventas-service
          uri: lb://mensaje-service
          predicates:
           - Path=/api/mensaje/**
          filters:
            - StripPrefix=2